services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    build: ./fe
    volumes:
      - /Users/adimi/repos/typescript-playground/fe:/usr/share/nginx/html
    ports: 
      - 8000:80